linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true

linters:
  enable-all: true
  disable:
  - maligned # Deprecated, see govet's fieldalignment instead.
  - exhaustivestruct # Deprecated.  Owner disappeared.  See exhaustruct.
  - golint # Deprecated.  Archived by owner.  See revive.
  - scopelint # Deprecated.  Archived by owner.  See exportloopref.
  - interfacer # Deprecated.  Archived by owner.
  # The following are disabled pending 1.18 support.  See: https://github.com/golangci/golangci-lint/issues/2649
  - bodyclose
  - contextcheck
  - nilerr
  - noctx
  - rowserrcheck
  - sqlclosecheck
  - structcheck
  - tparallel
  - unparam
  - wastedassign
  # And the following are turned off because I'm not sure they're helpful:
  - exhaustruct

run:
  deadline: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
